routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
///// Route Admin
Route::namespace("App\Http\Controllers\Admin\Auth")->group(function () {
    Route::get('login', 'LoginController@loginForm')->name('admin.login.form');
    Route::post('login', 'LoginController@login')->name('admin.login');
});
Route::namespace("App\Http\Controllers\Admin")->group(function () {
    Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('dashboard', "AdminController@dashboard")->name('admin.dashboard');
    Route::get('support', "AdminController@support_form")->name('admin.support_form');
    Route::post('support', "AdminController@support")->name('admin.support');
    Route::get('laws', "AdminController@laws_form")->name('admin.laws_form');
    Route::post('laws', "AdminController@laws")->name('admin.laws');

    Route::get('setting', "SettingController@form")->name('admin.setting');
    Route::post('setting/monetary-unit', "SettingController@monetary_unit")->name('admin.setting.monetary-unit');
    Route::post('setting/trade-swap-status', "SettingController@trade_swap_status")->name('admin.setting.trade-swap-status');
    Route::post('setting/admin-notifs-status','SettingController@admin_notifs_status')->name('admin.setting.notifs-status');

    Route::get('wd-currency-setting','CurrencyController@form')->name('admin.wd-currency-setting');
    Route::post('wd-currency-status','CurrencyController@wd_currency_status')->name('admin.wd-currency-status');
//    Route::get('manage-withdraw-swap-page', 'AdminController@manage_withdraw_swap_page')->name('manage-withdraw-swap-page');
//    Route::post('manage_withdraw_update', 'AdminController@manage_withdraw_update')->name('manage-withdraw-update');
//    Route::post('manage-swap-currency', 'AdminController@manage_swap_update')->name('manage-swap-update');
    Route::post('change-unit', 'AdminController@change_unit')->name('change-unit');
    Route::post('change-unit-for-withdraw', 'AdminController@change_unit_for_withdraw')->name('change-unit-for-withdraw');

    Route::post('withdraw-rial/reject/{id}', 'WithdrawRialController@reject')->name('admin.withdraw-rial.reject');
    Route::post('withdraw-rial/confirm/{id}', 'WithdrawRialController@confirm')->name('admin.withdraw-rial.confirm');
    Route::resource('withdraw-rial', 'WithdrawRialController', ['as' => 'admin']);


    // مدیریت کارمزد ها
    Route::get('manage/fees', "AdminController@fees_index")->name('admin.manage.fees.index');
    Route::post('manage/fees', "AdminController@fees_store")->name('admin.manage.fees.store');


    //    TRADE MANAGE
//    Route::get('trade-management', 'AdminController@manage_trade_page')->name('trade-management');
//    Route::post('trade-fee-update', 'AdminController@trad_fee_update')->name('trad-fee-update');
//    Route::post('trade-fees-update', 'AdminController@trad_fees_update')->name('trad-fees-update'); // اینو خانم سواری گفت post کنم
    Route::get('get-currency-fees', 'AdminController@get_currency_fees')->name('get-currency-fees');
    Route::get('set-fees', 'AdminController@set_fees')->name('set-fees');

    Route::get('users', 'UserController@index')->name('user.index');
    Route::get('users/authenticate/{user}', 'UserController@form_authenticate')->name('user.authenticate.form');
    Route::get('users/authenticate', 'UserController@authenticate')->name('user.authenticate.index');
    Route::get('users/{user}', 'UserController@show')->name('user.show');
    Route::post('users/{user}/wallet', 'UserController@wallet')->name('admin.users.wallet');
    Route::get('user/changeStatus', 'UserController@change_status');
    Route::post('user/{user}/edit', 'UserController@edit')->name('admin.user.edit');
//    Route::post('user/{user}/role', 'UserController@role')->name('admin.user.manage-role');
    Route::get('user/{user}/login-panel', 'UserController@login_panel')->name('admin.user.login-panel');
    Route::get('user/disableStatus', 'UserController@disable_status');
    Route::get('tickets', 'TicketController@index')->name('ticket.admin.index');
    Route::get('ticket/create', 'TicketController@create')->name('ticket.admin.create');
    Route::post('ticket/store', 'TicketController@store')->name('ticket.admin.store');
    Route::get('my_tickets', 'TicketController@index')->name('my_ticket.admin.index');
    Route::get('ticket/{id}', 'TicketController@show')->name('ticket.admin.show');
    Route::get('ticket/ban/{id}', 'TicketController@ban')->name('ticket.admin.ban');
    Route::get('get-users', 'TicketController@users')->name('admin.users');
    Route::delete('ticket/destroy/{id}', 'TicketController@destroy')->name('ticket.destroy');
    Route::post('ticket/route/{id}', 'TicketController@route')->name('ticket.route');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.admin.store');
    Route::resource('currencies', 'CurrencyController');
    Route::get('roles', "RolesController@index")->name('roles.index');
    Route::get('roles/create', "RolesController@create")->name('roles.create');
    Route::post('roles/store', "RolesController@store")->name('roles.store');
    Route::get('roles/{id}/edit', "RolesController@edit")->name('roles.edit');
    Route::post('roles/{id}/update', "RolesController@update")->name('roles.update');
    Route::delete('roles/delete', "RolesController@destroy")->name('roles.destroy');
    Route::get('banks', 'BankController@index')->name('admin.bank.index');
    Route::post('banks/{bank}/confirm', 'BankController@confirm')->name('admin.bank.confirm');
    Route::post('banks/{bank}/reject', 'BankController@reject')->name('admin.bank.reject');
    Route::resource('notifications', 'NotificationController');
    Route::get('get-user', 'NotificationController@users')->name('notifications.get_user');
    Route::get('reports', 'ReportController@index')->name('admin.report.index');
    Route::resource('posts', 'PostController');
    Route::post('posts/reject', 'PostController@reject')->name('posts.reject');
    Route::post('posts/accept', 'PostController@accept')->name('posts.accept');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/delete', 'CategoryController@delete')->name('categories.delete');
//    Route::post('manage-fee-withdraw-admin-update', 'AdminController@fee_withdraw_admin_update')->name('manage-fee-withdraw-admin-update');
    Route::get('request/withdraw', 'WDController@index_withdraw')->name('admin.request.withdraw');
    Route::get('request/withdraw/{id}/show', 'WDController@show_withdraw')->name('admin.request.withdraw.show');
    Route::post('request/withdraw/balance/admin', 'WDController@balance_admin')->name('admin.request.withdraw.balance-admin');
    Route::post('request/withdraw/update-status', 'WDController@update_status')->name('admin.request.withdraw.update-status');

    Route::resource('announcements','AnnouncementController')->names('admin.ann');
});

routes/web.php
    Route::get('auth/register', 'LoginRegisterController@register')->name('register.form');
    Route::post('auth/register/store', 'LoginRegisterController@registerStore')->name('register.store');
    Route::get('forget-password', 'LoginRegisterController@forgetPasswordForm')->name('login.forget_password.form');
    Route::post('forget-password', 'LoginRegisterController@forgetPasswordSendEmail')->name('login.forget_password.send');
    Route::post('forget-change-password', 'LoginRegisterController@forgetChangePassword')->name('login.forget_password.change-password');
    Route::get('/login', 'GoogleController@loginWithGoogle')->name('login');
    Route::get('callback', 'GoogleController@callbackFromGoogle')->name('callback');
});
// SIGN IN WITH GOOGLE ROUTES
//Route::prefix('google')->name('google.')->group( function(){
//    Route::get('/login', ['GoogleController@loginWithGoogle'])->name('login');
//    Route::get('/callback', ['GoogleController@callbackFromGoogle'])->name('callback');
//});
// END
Route::get('verify-email/token/{token}', "App\Http\Controllers\User\StepsController@verifyEmail")->name('step.verify-token.email');
/// Route Landing
Route::namespace("App\Http\Controllers\Landing")->group(function () {
    Route::get('/', 'HomeController@index')->name('landing.home');
    Route::get('/join', 'HomeController@test');
    Route::get('/about-rootix', 'HomeController@about')->name('landing.about');
    Route::get('/blog-page', 'HomeController@blog')->name('landing.blog');
    Route::get('/services', 'HomeController@services')->name('landing.services');
    Route::get('/faq', 'HomeController@faq')->name('landing.faq');
    Route::get('/education', 'HomeController@education')->name('landing.education');
    Route::get('/prices', 'HomeController@prices')->name('landing.prices');
    Route::get('/price-detail/{currency}', 'HomeController@price_detail')->name('landing.price_detail');
    Route::get('/chart', 'HomeController@chart')->name('landing.chart');
    Route::get('/post/{slug}', 'HomeController@post_show')->name('landing.post');
    Route::get('/search', 'HomeController@post_search')->name('landing.search');
    Route::get('/contact-rootix', 'HomeController@contact_us')->name('landing.contact_us');
    Route::get('/rootix-laws', 'HomeController@rootix_laws')->name('landing.laws');

});

Route::get('withdraw/token/{token}', "App\Http\Controllers\User\WithdrawController@verifyEmail")->name('verify-withdraw.email');
Route::get('reject/token/{token}', "App\Http\Controllers\User\WithdrawController@rejectEmail")->name('reject-withdraw.email');


///// Route User
Route::middleware(['auth', 'steps', '2fa'])->namespace("App\Http\Controllers\User")->group(function () {
    ///// Route Step
    Route::prefix('step')->group(function () {
        Route::get('verify-mobile', "StepsController@mobile")->name('step.verify-mobile');
        Route::get('verify-email', "StepsController@email")->name('step.verify-email');
        Route::post('verify-mobile/send-verify', "StepsController@sendVerify")->name('step.send-verify');
        Route::post('verify-email/send-link', "StepsController@sendEmail")->name('step.send-email');
        Route::get('information', "StepsController@information")->name('step.information');
        Route::post('information/store', "StepsController@informationStore")->name('step.information.store');
        Route::get('bank', "StepsController@bank")->name('step.bank');
        Route::post('bank/store', "StepsController@bankStore")->name('step.bank.store');
        Route::get('upload_document', "StepsController@uploadDocuments")->name('step.upload');
        Route::post('upload_document/store', "StepsController@uploadDocumentsStore")->name('step.upload.store');
        Route::get('finish', "StepsController@finish")->name('step.finish');
    });

    Route::post('google2fa/authenticate', function () {
        return redirect(\route('user.dashboard'));
    });
    Route::get('dashboard', "HomeController@dashboard")->name('user.dashboard');
    Route::get('profile', "ProfileController@formProfile")->name('user.profile.form');
    Route::post('profile/about/{id}', "ProfileController@update")->name('profile.update.about');
//    Route::get('swap/{unit}', 'SwapController@show')->name('swap.show');


    Route::get('swap', 'SwapController@index')->name('swap.index');
    Route::post('swap', 'SwapController@store')->name('swap.store');


    Route::post('get-list-currencies', 'AssetController@list_currencies')->name('asset.get_list_currencies');
//    Route::post('get-unit-price', 'SwapController@get_unit_price')->name('get-unit-price');
//    Route::post('get-unit-swap-fee-price', 'SwapController@get_unit_swap_fee_price')->name('get-unit-swap-fee-price');
    Route::post('get_theter_price', 'HomeController@get_theter_price')->name('get_theter_price');
//    Route::post('exchange', 'SwapController@exchange')->name('exchange');
    Route::post('createAccount/{unit}', 'ProfileController@wallet')->name('createAccount');
//    Route::post('check-withdraw-amount', 'WithdrawController@check_withdraw_amount')->name('check-withdraw-amount');
//    Route::post('withdraw-from-wallet', 'WithdrawController@withdraw_from_wallet')->name('withdraw-from-wallet');
//    Route::post('send-message-admin', 'WithdrawController@send_message_admin')->name('send-message-admin');
    Route::post('get-total-usdt', 'WithdrawController@get_total_usdt')->name('get-total-usdt');
//    Route::get('withdraw/{unit}','WithdrawController@index')->name('withdraw.index');
//    Route::post('withdraw','WithdrawController@store')->name('withdraw.store');
    Route::get('withdraw/token/{token}', "WithdrawController@verifyEmail")->name('verify-withdraw.email');

//    Route::resource('withdraw-rial','WithdrawRialController');
    Route::get('wallet/withdraw/rial', 'WDController@W_withdraw_index_rial')->name('wallet.withdraw.rial.index');
    Route::get('wallet/withdraw/rial/create', 'WDController@W_withdraw_create_rial')->name('wallet.withdraw.rial.create');
    Route::post('wallet/withdraw/rial', 'WDController@W_withdraw_store_rial')->name('wallet.withdraw.rial.store');

    Route::get('wallet/deposit/rial/create', 'WDController@W_deposit_create_rial')->name('wallet.deposit.rial.create');
    Route::post('wallet/deposit/rial', 'WDController@W_deposit_store_rial')->name('wallet.deposit.rial.store');

    Route::get('reject/token/{token}', "WithdrawController@rejectEmail")->name('reject-withdraw.email');
    Route::get('change-pass', 'ProfileController@change_pass_view')->name('change_pass.index');
    Route::post('change-pass', 'ProfileController@change_pass')->name('change_pass.store');
    Route::get('/charge-wallet', '\App\Http\Controllers\General\PaymentController@chargeWallet')->name('charge_wallet.view');
    Route::resource('tickets', 'TicketController');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.store');
    Route::post('/setting/change_confirmation_type', 'SettingController@change_confirmation_type')->name('setting.change_confirmation_type');
    Route::post('/setting/verify_confirmation_type', 'SettingController@verify_confirmation_type')->name('setting.verify_confirmation_type');
    Route::get('setting', 'SettingController@form')->name('setting.form');
    Route::post('/setting/status-google-authenticator', 'SettingController@status_google_authenticator')->name('setting.status_google_authenticator');
    Route::post('/setting/login_2fa', 'SettingController@login_2fa')->name('setting.login_2fa');

    Route::get('/sell-currency', 'SellBuyController@sellCurrencyView')->name('sell_currency.view');
    Route::post('get-user-assets', 'AssetController@get_user_assets');
    Route::resource('wallet', 'AssetController');
    Route::post('wallet/refresh', 'AssetController@refresh_wallet')->name('wallet.refresh');
    Route::resource('banks', 'BankController')->middleware("can:user-check,bank");
    Route::post('banks/{bank}', 'BankController@update_bank')->name('banks.update.bank');
    Route::post('update-profile-picture/{user}', 'ProfileController@update_avatar')->name('profile.update.picture');
    Route::post('/complete-registration', 'ProfileController@completeRegistration')->name('complete-registration');
    Route::post('get-address-wallet', 'WDController@getAddressWallet')->name('wallet.get-address-wallet');
    Route::post('withdrawal-fee', 'WDController@WithdrawalFee')->name('wallet.withdrawal-fee');
    Route::post('withdraw', 'WDController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw/index','WDController@index')->name('withdraw.index');
    Route::get('wallet/deposit/{unit}', 'WDController@deposit_form')->name('deposit-form');
    Route::get('wallet/withdraw/{unit}', 'WDController@withdraw_form')->name('withdraw-form');
    Route::post('security-withdraw', 'WDController@security_withdraw')->name('withdraw.security');
    Route::post('security-send-sms', 'WDController@security_send_sms')->name('withdraw.send-sms');
    Route::get('transactions', 'TransactionController@index')->name('transactions.index');
    //Route::resource('notification', 'NotificationController')->names('notification');
    Route::delete('/notifications/clear_all', 'NotificationController@clear_all')->name('notifications.clear_all');
    Route::get('exchange/{des_unit}-{source_unit}', 'ExchangeController@index')->name('exchange.index');
    Route::post('exchange/new-trade', 'ExchangeController@new_trade')->name('exchange.new-trade');
    Route::get('exchange/cancel-trade/{id}', 'ExchangeController@cancel_trade')->name('exchange.cancel-trade');
    Route::post('exchange/list-request','ExchangeController@list_request')->name('exchange.list-request');
    Route::post('exchange/last-transaction','ExchangeController@last_transaction')->name('exchange.list-transaction');
    Route::post('exchange/markets','ExchangeController@markets')->name('exchange.list-markets');

resources/views/user-old/bank/create.blade.php
@extends('templates.user.master_page')
@section('title_browser')
    {{ isset($bank) && $bank?__('titlePage.title-bankEdit'):__('titlePage.title-bankNew') }}
@endsection

@section('content')
    <div class="settings mtb15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 m-auto col-12 row">
                    <div class="row col-12 bg-dark-2 text-light"
                         style="min-height: 200px; margin-bottom: -50px; padding-bottom: 40px; border-radius: 3px;">
                        <div class="col-12 row align-items-end m-auto">
                            <div class="col row  m-auto">
                                <div class="">
                                    <img src="{{asset('theme/user/assets/img/add-icon.png')}}" alt="logo" width="90"
                                         height="80">
                                </div>
                                <h3 class="col my-3 d-flex flex-row align-items-center text-white">{{ isset($bank)?__('titlePage.title-bankEdit'):__('titlePage.title-bankNew')  }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-8 text-dark ">
                        <div class="card">
                            <div class="card-body">
                                <div class="card overflow-hidden">
                                    <div class="card-content">
                                        <div class="card-body">
                                            <form class="col-10 mx-auto" method="post"
                                                  action=" {{ isset($bank) ? route('banks.update',$bank):route('banks.store') }}">
                                                @csrf
                                                @if(isset($bank))
                                                    @method('put')
                                                @endif
                                                <fieldset>
                                                    <div class="form-group">
                                                        <label class="py-1">{{__('attributes.bank.bankName')}}
                                                            <sub class="text-danger">*</sub>
                                                        </label>
                                                        <select name="name" class="form-control custom-select">
                                                            <option disabled value="" selected>{{__('attributes.bank.bankSelect')}}
                                                            </option>
                                                            @foreach(banks_name() as $item)
                                                                <option
                                                                    value="{{ $item }}" name="name"
                                                                    @if(isset($bank) && $bank->name == $item) selected @endif>{{ $item }}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="py-1">{{__('attributes.bank.cardNum')}}
                                                            <sub class="text-danger">*</sub>
                                                        </label>
                                                        <input type="number" name="card_number"
                                                               value="{{ isset($bank) ? $bank->card_number: '' }}"
                                                               class="form-control"
                                                               placeholder="{{__('attributes.bank.example')}}: 1235414525688745">
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="py-1">{{__('attributes.bank.accountNumber')}}
                                                            <sub class="text-danger">*</sub>
                                                        </label>
                                                        <input type="number" name="account_number"
                                                               value="{{ isset($bank) ? $bank->account_number: '' }}"
                                                               class="form-control"
                                                               placeholder="{{__('attributes.bank.example')}}: 123456789101">
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="py-1">{{__('attributes.bank.shaba')}}
                                                            <sub class="text-danger">*</sub><br>
                                                            <sub class="text-primary">{{__('attributes.bank.shabaIR')}}</sub>
                                                        </label>
                                                        <input type="text" name="sheba_number"
                                                               value="{{ isset($bank) ? $bank->sheba_number: '' }}"
                                                               class="form-control"
                                                               placeholder="{{__('attributes.bank.example')}}: IR421234567891234567891255">
                                                    </div>
                                                    <div class="form-group">
                                                        <button type="button"
                                                                class="btn btn-info d-block mx-auto px-4 ajaxStore">{{ isset($bank) ? __('attributes.bank.accountEdit'):__('attributes.bank.accountNew') }}</button>
                                                    </div>
                                                </fieldset>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4 card ">
                        <div class="card-body">
                            <p class="alert alert-info">
                                در صورت تمایل اینجا میشه برای افزایش موجودی متنی اگه لازم بود گذاشت
                            </p>
                            <div class="video mx-auto">
                                <video style="width: 100%;" height="240" controls>
                                    <source src="movie.mp4" type="video/mp4">
                                    <source src="movie.ogg" type="video/ogg">
                                    مرورگر شما از این قابلیت پشتیبانی نمی کند
                                </video>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user-old/bank/index.blade.php
@extends('templates.user.master_page')
@section('title_browser')
    {{__('titlePage.title-accountBank')}}
@endsection
@section('style')
    <style>
        .question-icon {
            display: inline-block;
            vertical-align: text-top;

        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css-rtl/pages/data-list-view.min.css') }}">
@endsection
@section('content')
    <section id="data-list-view" class="data-list-view-header">
        <div class="action-btns d-none">
            <div class="btn-dropdown mr-1 mb-1">
                <div class="btn-group dropdown actions-dropodown">
                    <button type="button" class="btn btn-white px-1 py-1 dropdown-toggle waves-effect waves-light"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false"> {{__('attributes.bank.actions')}}
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#"><i
                                class="feather icon-trash"></i>{{__('attributes.bank.delete')}}</a>
                        <a class="dropdown-item" href="#"><i
                                class="feather icon-archive"></i>{{__('attributes.bank.archive')}}</a>
                        <a class="dropdown-item" href="#"><i
                                class="feather icon-file"></i>{{__('attributes.bank.print')}}</a>
                        <a class="dropdown-item" href="#"><i
                                class="feather icon-save"></i>{{__('attributes.bank.other')}}</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-2 col-12">
            <a href="{{ route('banks.create') }}" class="btn btn-info">{{__('attributes.bank.addBank')}}</a>
        </div>

        <!-- DataTable starts -->
        <div class="table-responsive card card-body ">
            <table class="table table-striped table-hover-animation">
                <thead>
                <tr>
                    <th></th>
                    <th>{{__('attributes.bank.name')}}</th>
                    <th>{{__('attributes.bank.cardNum')}}</th>
                    <th>{{__('attributes.bank.accountNumber')}}</th>
                    <th>{{__('attributes.bank.shaba')}}</th>
                    <th>وضعیت</th>
                    <th>{{__('attributes.bank.date')}}</th>
                    <th>{{__('attributes.bank.actions')}}</th>
                </tr>
                </thead>
                <tbody>
                @if (count($banks) > 0)
                    @foreach($banks as $i=>$bank)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $bank->name }}</td>
                            <td>{{ $bank->card_number }}</td>
                            <td>{{ $bank->account_number }}</td>
                            <td>{{ $bank->sheba_number }}</td>
                            <td>
                                <span class="badge badge-{{ $bank->status_color }}">
                                    {{ $bank->status_text }}
                                </span>
                                @if ($bank->status == 3)
                                    <sub  data-toggle="tooltip" title="{{ $bank->reject_reason }}" class="badge badge-pill badge-danger animate__animated animate__fadeOut animate__infinite infinite question-icon">
                                        <i class="fa fa-question text-white"></i>
                                    </sub>
                                @endif
                            </td>
                            <td>{{ jdate_from_gregorian($bank->created_at,'Y/m/d') }}</td>
                            <td class="product-action">
                                <span class="action-edit" style="cursor: pointer"><a
                                        href="{{ route('banks.edit',$bank) }}" class="feather icon-edit"></a></span>
                                <span style="cursor: pointer"><a data-icon="warning"
                                                                 data-text="{{__('attributes.bank.errDelete')}}"
                                                                 data-confirm="{{__('attributes.bank.deleteFunction')}}"
                                                                 data-action="{{ route('banks.destroy', $bank) }}"
                                                                 data-method="delete"
                                                                 class="feather icon-trash text-danger"></a></span>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="15" class="text-center">{{__('attributes.bank.display')}}</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
        <!-- DataTable ends -->
    </section>
@endsection